# Project information
site_name: Forgotten Sunnah
site_description: >-
  Are you striving to get closer to Allah? We can try to help, inshaAllah. 
  Subscribe to receive reminders on forgotten sunnah, hadith, tafseer of Quran 
  by bn Kathir, quotes of scholars and beneficial ilm, inshaAllah.

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Customization
extra:
  analytics:
    provider: google
    property: G-91MF1FEMTM