site_name: Forgotten Sunnah
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.path
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences